version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfg
      POSTGRES_DB: news_database
    ports:
      - "5438:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
